id: P31453955
initial_creation_type: ocr
source_metadata:
  volumes:
    23bd044100d34205be02622bf4e1ac89:
      base_file: v116.txt
      image_group_id: I1PD95961
      title: རྡོ་རྗེའི་སྨོན་ལམ།
      total_pages: 1880
      volume_number: 116
